old examples/rails/csc3100_demos/test_app/config/routes.rb
Rails.application.routes.draw do
  resources :lost_forms
  resources :pet_forms
  devise_for :admins
  devise_for :users

  root to: "dashboard#index"

  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'
	
  get 'dashboard/adoptable'

  get 'dashboard/resources'

  get 'dashboard/support'

  get 'dashboard/lost_pets'

  get 'dashboard/found_pets'

  get 'dashboard/lost_form'

  get 'dashboard/found_form'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

old examples/rails/csc3100_demos/test_app/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

old examples/rails/csc3100_demos/test_app/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :lockable
end

old examples/rails/csc3100_demos/test_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

old examples/rails/csc3100_demos/test_app/app/models/lost_form.rb
class LostForm < ApplicationRecord
end

old examples/rails/csc3100_demos/test_app/app/models/pet_form.rb
class PetForm < ApplicationRecord
end

old examples/rails/csc3100_demos/test_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

old examples/rails/csc3100_demos/test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit( :email, :first_name, :last_name, :password, :password_confirmation, :remember_me)}
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :password, :password_confirmation, :current_password, :remember_me)}
  end

end

old examples/rails/csc3100_demos/test_app/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def page1
  end

  def page2
  end

   def adoptable
  end

  def resources
  end

  def support
  end

  def lost_pets
    @lost_forms = LostForm.all
  end

  def found_pets
    @pet_forms = PetForm.where(pending = false)
  end

  def lost_form
  end

  def found_form
  end
end

old examples/rails/csc3100_demos/test_app/app/controllers/lost_forms_controller.rb
class LostFormsController < ApplicationController
  before_action :set_lost_form, only: [:show, :edit, :update, :destroy]

  # GET /lost_forms
  # GET /lost_forms.json
  def index
    @lost_forms = LostForm.all
  end

  # GET /lost_forms/1
  # GET /lost_forms/1.json
  def show
  end

  # GET /lost_forms/new
  def new
    @lost_form = LostForm.new
  end

  # GET /lost_forms/1/edit
  def edit
  end

  # POST /lost_forms
  # POST /lost_forms.json
  def create
    @lost_form = LostForm.new(lost_form_params)

    respond_to do |format|
      if @lost_form.save
        format.html { redirect_to @lost_form, notice: 'Lost form was successfully created.' }
        format.json { render :show, status: :created, location: @lost_form }
      else
        format.html { render :new }
        format.json { render json: @lost_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lost_forms/1
  # PATCH/PUT /lost_forms/1.json
  def update
    respond_to do |format|
      if @lost_form.update(lost_form_params)
        format.html { redirect_to @lost_form, notice: 'Lost form was successfully updated.' }
        format.json { render :show, status: :ok, location: @lost_form }
      else
        format.html { render :edit }
        format.json { render json: @lost_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lost_forms/1
  # DELETE /lost_forms/1.json
  def destroy
    @lost_form.destroy
    respond_to do |format|
      format.html { redirect_to lost_forms_url, notice: 'Lost form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lost_form
      @lost_form = LostForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lost_form_params
      params.require(:lost_form).permit(:current_date, :lost_date, :phone, :owner_name, :pet_name, :collar, :tags, :color, :species, :breed, :gender, :size, :spayed_neutered, :found, :comments)
    end
end

old examples/rails/csc3100_demos/test_app/app/controllers/pet_forms_controller.rb
class PetFormsController < ApplicationController
  before_action :set_pet_form, only: [:show, :edit, :update, :destroy]

  # GET /pet_forms
  # GET /pet_forms.json
  def index
    @pet_forms = PetForm.all
  end

  # GET /pet_forms/1
  # GET /pet_forms/1.json
  def show
  end

  # GET /pet_forms/new
  def new
    @pet_form = PetForm.new
  end

  # GET /pet_forms/1/edit
  def edit
  end

  # POST /pet_forms
  # POST /pet_forms.json
  def create
    @pet_form = PetForm.new(pet_form_params)

    respond_to do |format|
      if @pet_form.save
        format.html { redirect_to @pet_form, notice: 'Pet form was successfully created.' }
        format.json { render :show, status: :created, location: @pet_form }
      else
        format.html { render :new }
        format.json { render json: @pet_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_forms/1
  # PATCH/PUT /pet_forms/1.json
  def update
    respond_to do |format|
      if @pet_form.update(pet_form_params)
        format.html { redirect_to @pet_form, notice: 'Pet form was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_form }
      else
        format.html { render :edit }
        format.json { render json: @pet_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_forms/1
  # DELETE /pet_forms/1.json
  def destroy
    @pet_form.destroy
    respond_to do |format|
      format.html { redirect_to pet_forms_url, notice: 'Pet form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_form
      @pet_form = PetForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_form_params
      params.require(:pet_form).permit(:date, :date_since, :phone, :owner_name, :pet_name, :color, :collar, :tags, :breed, :gender, :size, :spayed_neutered, :area, :comments, :lost_found, :pending)
    end
end

old examples/rails/csc3100_demos/test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

old examples/rails/csc3100_demos/test_app/app/helpers/dashboard_helper.rb
module DashboardHelper
end

old examples/rails/csc3100_demos/test_app/app/helpers/layout_helper.rb
module LayoutHelper

	def bootstrap_version
		# Choose the Bootstrap version you would like to use from the CDN
		"3.0.3"
	end

end

old examples/rails/csc3100_demos/test_app/app/helpers/lost_forms_helper.rb
module LostFormsHelper
end

old examples/rails/csc3100_demos/test_app/app/helpers/pet_forms_helper.rb
module PetFormsHelper
end

old examples/rails/csc3100_demos/test_app/app/views/dashboard/adoptable.html.erb
<h1>Coming Soon!</h1>

<h2>Images and Descriptions of Current available animals at CPCAS!</h2>

<br><br><br><br><br><br><br><br><br><br><br><br>

old examples/rails/csc3100_demos/test_app/app/views/dashboard/found_form.html.erb
<h1>Found Pet Form</h1>

<%= render 'form', pet_form: @pet_form %>

old examples/rails/csc3100_demos/test_app/app/views/dashboard/found_pets.html.erb
<h1>Found Pets</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Date since</th>
      <th>Phone</th>
      <th>Owner name</th>
      <th>Pet name</th>
      <th>Color</th>
      <th>Collar</th>
      <th>Tags</th>
      <th>Breed</th>
      <th>Gender</th>
      <th>Size</th>
      <th>Spayed neutered</th>
      <th>Area</th>
      <th>Comments</th>
      <th>Lost found</th>
      <th>Pending</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pet_forms.each do |pet_form| %>
      <tr>
        <td><%= pet_form.date %></td>
        <td><%= pet_form.date_since %></td>
        <td><%= pet_form.phone %></td>
        <td><%= pet_form.owner_name %></td>
        <td><%= pet_form.pet_name %></td>
        <td><%= pet_form.color %></td>
        <td><%= pet_form.collar %></td>
        <td><%= pet_form.tags %></td>
        <td><%= pet_form.breed %></td>
        <td><%= pet_form.gender %></td>
        <td><%= pet_form.size %></td>
        <td><%= pet_form.spayed_neutered %></td>
        <td><%= pet_form.area %></td>
        <td><%= pet_form.comments %></td>
        <td><%= pet_form.lost_found %></td>
        <td><%= pet_form.pending %></td>
        <td><%= link_to 'Show', pet_form %></td>
        <td><%= link_to 'Edit', edit_pet_form_path(pet_form) %></td>
        <td><%= link_to 'Destroy', pet_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet Form', new_pet_form_path %>

old examples/rails/csc3100_demos/test_app/app/views/dashboard/index.html.erb
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

<div class="container text-center" id="mycolumn">
	<div class="row">
		<div class="col-md-6">
			<h3>
			<address> 
				 <!-- Phone encryption at http://thenetweb.co.uk/obfuscate-hide-and-obscure-e-mail-addresses-telephone-numbers-and-text-->
				 <strong>Cookeville Putnam County Animal Shelter</strong><br /> 2650 Gainesboro Grade<br /> Cookeville, TN 38501<br /> <abbr title="Phone">P: </abbr>&#40;&#57;&#51;&#49;&#41;&#32;&#53;&#50;&#54;&#32;&#45;&#32;&#51;&#54;&#52;&#55;
			</address>
			</h3> 
		</div>
		<div class="col-md-6">
			<!-- <img alt="Animal Shelter Picture" src="https://lh3.googleusercontent.com/-aZawp6qimtA/VmiO8v-3YtI/AAAAAAAAAAk/cxy-rdXEOOMU-o5LDkfBlN2lHLdpX00CQCL0B/w692-h389-n-no/cpcas.jpg" style="width:auto;height:300px;" /> -->
			<!-- Changed image so that it is using the image in "images" folder instead of using the url. -->
				<%=  image_tag 'cpcas.jpg', style: "width:auto;height:300px;" %>
		</div>
	</div>
 </div>
	
	<div class="container text-center">
		<div class="row " id="indexBody">
	    	<div class="col-md-2" id="mycolumn">
				<div id="googleMap" style="width:auto;height:300px;"></div>

            		<script>
            			function myMap() {
            			var mapProp= {
                			center:new google.maps.LatLng(36.201942, -85.534520),
                			zoom:15,
            				};
           				var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
            			}
            		</script>
            
            <script defer src="https://maps.googleapis.com/maps/api/js?key= AIzaSyAYwGnMGsji6ZIa8mMHsz6nsE4_BXqA-Ow &callback=myMap" type="text/javascript"></script>
  			</div>
  			
			<div class="col-md-2" id="mycolumn">
			    <div class="fb-page" data-href="https://www.facebook.com/cpcas/" data-tabs="timeline" data-width="400" data-small-header="false" data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="false"><blockquote cite="https://www.facebook.com/cpcas/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/cpcas/">Cookeville / Putnam County Animal Shelter</a></blockquote></div>
			<p class = borderexample>
				
			</p>
			</div>
		</div>
	</div>
<br><br><br><br><br><br>

old examples/rails/csc3100_demos/test_app/app/views/dashboard/lost_form.html.erb
<h1>Coming Soon!</h1>

<h2>Post a Lost pet in our community!</h2>

<br><br><br><br><br><br><br><br><br><br><br><br>

old examples/rails/csc3100_demos/test_app/app/views/dashboard/lost_pets.html.erb
<h1>Lost Pets</h1>

<% if current_user.try(:admin?) %>
<table>
  <thead>
    <tr>
      <th>Current date</th>
      <th>Lost date</th>
      <th>Phone</th>
      <th>Owner name</th>
      <th>Pet name</th>
      <th>Collar</th>
      <th>Tags</th>
      <th>Color</th>
      <th>Species</th>
      <th>Breed</th>
      <th>Gender</th>
      <th>Size</th>
      <th>Spayed/neutered</th>
      <th>Found</th>
      <th>Comments</th>
      <% if current_user.try(:admin?) %>
      <th>Pending</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lost_forms.each do |lost_form| %>
      <tr>
        <td><%= lost_form.current_date %></td>
        <td><%= lost_form.lost_date %></td>
        <td><%= lost_form.phone %></td>
        <td><%= lost_form.owner_name %></td>
        <td><%= lost_form.pet_name %></td>
        <td><%= lost_form.collar %></td>
        <td><%= lost_form.tags %></td>
        <td><%= lost_form.color %></td>
        <td><%= lost_form.species %></td>
        <td><%= lost_form.breed %></td>
        <td><%= lost_form.gender %></td>
        <td><%= lost_form.size %></td>
        <td><%= lost_form.spayed_neutered %></td>
        <td><%= lost_form.found %></td>
        <td><%= lost_form.comments %></td>
        <% if current_user.try(:admin?) %>
        <td><%= lost_form.pending %></td>
        <td><%= link_to 'Show', lost_form %></td>
        <td><%= link_to 'Edit', edit_lost_form_path(lost_form) %></td>
        <td><%= link_to 'Destroy', lost_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% else %>
<table>
  <thead>
    <tr>
      <th>Current date</th>
      <th>Lost date</th>
      <th>Phone</th>
      <th>Owner name</th>
      <th>Pet name</th>
      <th>Collar</th>
      <th>Tags</th>
      <th>Color</th>
      <th>Species</th>
      <th>Breed</th>
      <th>Gender</th>
      <th>Size</th>
      <th>Spayed/neutered</th>
      <th>Found</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lost_forms.each do |lost_form| %>
      <% if @lost_form.try(:pending?) %>
      <tr>
        <td><%= lost_form.current_date %></td>
        <td><%= lost_form.lost_date %></td>
        <td><%= lost_form.phone %></td>
        <td><%= lost_form.owner_name %></td>
        <td><%= lost_form.pet_name %></td>
        <td><%= lost_form.collar %></td>
        <td><%= lost_form.tags %></td>
        <td><%= lost_form.color %></td>
        <td><%= lost_form.species %></td>
        <td><%= lost_form.breed %></td>
        <td><%= lost_form.gender %></td>
        <td><%= lost_form.size %></td>
        <td><%= lost_form.spayed_neutered %></td>
        <td><%= lost_form.found %></td>
        <td><%= lost_form.comments %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

old examples/rails/csc3100_demos/test_app/app/views/dashboard/page1.html.erb
<h1>Dashboard#page1</h1>
<p>Find me in app/views/dashboard/page1.html.erb</p>

old examples/rails/csc3100_demos/test_app/app/views/dashboard/page2.html.erb
<h1>Dashboard#page2</h1>
<p>Find me in app/views/dashboard/page2.html.erb</p>

old examples/rails/csc3100_demos/test_app/app/views/dashboard/support.html.erb
<h1>Support Us</h1>


<div class="container text-center">
    <div class="row">
        
        <div class="col-md-6">
            <h2>Supply Donations</h2>
            <p>The Cookeville Putnam County Aminal Shelter is always in need of pet supplies, such as dog/cat food, cat liter, accident pads, and much more.</p>
            
            <h2>Alternate ways to donate</h2>
            <%=  image_tag 'donatepawprint.png', style: "width:auto;height:auto;" %>
            <!-- they have a token system operating the donations link, and the url that the site source shows simply directs me back to paypal's landing page -->
        </div>
        
        <div class="col-md-6">
            <h2>Volunteering</h2>
            <ul class="support_ul">
                <li>Directions</li>
                <li>1. Download and fill out the Volunteer Application.</li>
                <li>2. Download and fill out the Background Check form.</li>
                <li>3. Upon having these documents filled out, you may bring them into the Animal Shelter.</li>
                <br>
                <li>This process may take up to 2 weeks to complete, but upon completion you will recieve an email about training sessions.</li>
            </ul>
            <ul class="support_ul">
                <li>
                    <%= link_to "Background Check", '/documents/Background check.pdf', { :style => 'color: #0015FF' } %>
                </li>
                <li>
                    <%= link_to "Volunteer Application", '/documents/Volunteer Application.pdf', { :style => 'color: #0015FF' } %>
                </li>
                <li>
                    <%= link_to "Liability Waiver", '/documents/Liability waiver.pdf', { :style => 'color: #0015FF' } %>
                </li>
                <li>
                    <%= link_to "Liability Waiver (Minor)", '/documents/Liability waiver - Minor.pdf', { :style => 'color: #0015FF' } %>
                </li>
            </ul>
            
            <p>* Any form that requires a notary, please note that it should only be signed at the Animal Shelter.</p>
        </div>
        
    </div>
</div>

old examples/rails/csc3100_demos/test_app/app/views/lost_forms/_form.html.erb
<%= form_for(lost_form) do |f| %>
  <% if lost_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lost_form.errors.count, "error") %> prohibited this lost_form from being saved:</h2>

      <ul>
      <% lost_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :current_date %>
    <%= f.date_select :current_date %>
  </div>

  <div class="field">
    <%= f.label :lost_date %>
    <%= f.date_select :lost_date %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :owner_name %>
    <%= f.text_field :owner_name %>
  </div>

  <div class="field">
    <%= f.label :pet_name %>
    <%= f.text_field :pet_name %>
  </div>

  <div class="field">
    <%= f.label :collar %>
    <%= f.text_field :collar %>
  </div>

  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :species %>
    <%= f.text_field :species %>
  </div>

  <div class="field">
    <%= f.label :breed %>
    <%= f.text_field :breed %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.text_field :size %>
  </div>

  <div class="field">
    <%= f.label :spayed_neutered %>
    <%= f.text_field :spayed_neutered %>
  </div>

  <div class="field">
    <%= f.label :found %>
    <%= f.text_area :found %>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.text_area :comments %>
  </div>

  <% if !lost_form.new_record? %>
  <div class="field">
    <%= f.label :pending %>
    <%= f.text_field :pending %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

old examples/rails/csc3100_demos/test_app/app/views/lost_forms/edit.html.erb
<h1>Editing Lost Form</h1>

<%= render 'form', lost_form: @lost_form %>

<%= link_to 'Show', @lost_form %> |
<%= link_to 'Back', lost_forms_path %>

old examples/rails/csc3100_demos/test_app/app/views/lost_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lost Forms</h1>

<table>
  <thead>
    <tr>
      <th>Current date</th>
      <th>Lost date</th>
      <th>Phone</th>
      <th>Owner name</th>
      <th>Pet name</th>
      <th>Collar</th>
      <th>Tags</th>
      <th>Color</th>
      <th>Species</th>
      <th>Breed</th>
      <th>Gender</th>
      <th>Size</th>
      <th>Spayed neutered</th>
      <th>Found</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lost_forms.each do |lost_form| %>
      <tr>
        <td><%= lost_form.current_date %></td>
        <td><%= lost_form.lost_date %></td>
        <td><%= lost_form.phone %></td>
        <td><%= lost_form.owner_name %></td>
        <td><%= lost_form.pet_name %></td>
        <td><%= lost_form.collar %></td>
        <td><%= lost_form.tags %></td>
        <td><%= lost_form.color %></td>
        <td><%= lost_form.species %></td>
        <td><%= lost_form.breed %></td>
        <td><%= lost_form.gender %></td>
        <td><%= lost_form.size %></td>
        <td><%= lost_form.spayed_neutered %></td>
        <td><%= lost_form.found %></td>
        <td><%= lost_form.comments %></td>
        <td><%= link_to 'Show', lost_form %></td>
        <td><%= link_to 'Edit', edit_lost_form_path(lost_form) %></td>
        <td><%= link_to 'Destroy', lost_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lost Form', new_lost_form_path %>

old examples/rails/csc3100_demos/test_app/app/views/lost_forms/new.html.erb
<h1>New Lost Form</h1>

<%= render 'form', lost_form: @lost_form %>

<%= link_to 'Back', lost_forms_path %>

old examples/rails/csc3100_demos/test_app/app/views/lost_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Current date:</strong>
  <%= @lost_form.current_date %>
</p>

<p>
  <strong>Lost date:</strong>
  <%= @lost_form.lost_date %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lost_form.phone %>
</p>

<p>
  <strong>Owner name:</strong>
  <%= @lost_form.owner_name %>
</p>

<p>
  <strong>Pet name:</strong>
  <%= @lost_form.pet_name %>
</p>

<p>
  <strong>Collar:</strong>
  <%= @lost_form.collar %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @lost_form.tags %>
</p>

<p>
  <strong>Color:</strong>
  <%= @lost_form.color %>
</p>

<p>
  <strong>Species:</strong>
  <%= @lost_form.species %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @lost_form.breed %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @lost_form.gender %>
</p>

<p>
  <strong>Size:</strong>
  <%= @lost_form.size %>
</p>

<p>
  <strong>Spayed neutered:</strong>
  <%= @lost_form.spayed_neutered %>
</p>

<p>
  <strong>Found:</strong>
  <%= @lost_form.found %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @lost_form.comments %>
</p>

<%= link_to 'Edit', edit_lost_form_path(@lost_form) %> |
<%= link_to 'Back', lost_forms_path %>