old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  get 'about/index'

  get 'about' => 'about#index'

  root 'books#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers

end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = 'About Us';
  end
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add New Author'
    @author = Author.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add New Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add New Category'
    @category = Category.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add New Publisher'
    @publisher = Publisher.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/helpers/about_helper.rb
module AboutHelper
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/helpers/application_helper.rb
module ApplicationHelper
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/helpers/authors_helper.rb
module AuthorsHelper
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/helpers/books_helper.rb
module BooksHelper
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/helpers/categories_helper.rb
module CategoriesHelper
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/helpers/publishers_helper.rb
module PublishersHelper
end

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/views/authors/new.html.erb
<h2>Add New Author</h2>

<%= form_for @author do |f| %>

	<div class="form-group">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", authors_path, class:'btn btn-default' %>

<% end %>

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

old examples/rails/learn_rubyonrails_by_building/Program Files-5/bookstore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? @page_title : 'Welcome' %> | The BookStore</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
            <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>           
          </ul>
          <ul class="nav navbar-nav navbar-right">      
             <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Add New<span class="caret"></span></a>
          <ul class="dropdown-menu navbar-right" role="menu">
            <li><%=link_to "Book", new_book_path %></li>
            <li><%=link_to "Category", new_category_path %></li>
            <li><%=link_to "Author", new_author_path %></li>
            <li><%=link_to "Publisher", new_publisher_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <header>
    	<div class="container">
    		<h1>The BookStore <small><%= @page_title ? @page_title : 'Welcome' %></small></h1>
    	</div>
    </header>

    <section>
    	<div class="container">
    		<div class="row">
    			<div class="col-md-8">
					<%= yield %>
				</div>
				<div class="col-md-4">
					<%= render 'partials/sidebar' %>
				</div>
			</div>
		</div>
	</section>

	<footer>
		<div class="container">
			<p>Copyright &copy; 2014, All Rights Reserved</p>
		</div>
	</footer>

</body>
</html>